# Generated by Django 2.1.1 on 2018-09-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='TxHash',
            new_name='txHash',
        ),
    ]
