# Generated by Django 2.1.1 on 2018-09-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180913_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timeStamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
